coverage:
  settings:
    precision: 2
    round: down
    range: "70...100"
  status:
    project:
      default:
        threshold: 20%
    patch: off
    changes: off

github_checks:
  annotations: false

comment: false

ignore:
  - "docs"
  - "*.md"
  - "*.rst"
  - "DOCKER"
  - "scripts"
  - "*.yml"
  - "**/*.pb.go"
  - "libs/pubsub/query/query.peg.go"
