coverage:
  # Coverage reporting settings
  settings:
    precision: 2
    round: down
    range: "70...100"

  # Status checks configuration
  status:
    project:
      default:
        threshold: 20%
    patch: off
    changes: off

# GitHub integration
github_checks:
  annotations: false
comment: false

# Ignored paths and files
ignore:
  # Documentation
  - "docs"
  - "*.md"
  - "*.rst"
  
  # Build and deployment
  - "DOCKER"
  - "scripts"
  - "*.yml"
  
  # Generated code
  - "**/*.pb.go"
  - "libs/pubsub/query/query.peg.go"
