version: '3'

x-node-defaults: &node-defaults
  image: "cometbft/localnode"
  volumes:
    - ./build:/cometbft:Z
  environment:
    - LOG=${LOG:-cometbft.log}
  networks:
    localnet:
      ipv4_address: 192.167.10.2

services:
  node0:
    <<: *node-defaults
    container_name: node0
    environment:
      - ID=0
    ports:
      - "26656-26657:26656-26657"

  node1:
    <<: *node-defaults
    container_name: node1
    environment:
      - ID=1
    ports:
      - "26659-26660:26656-26657"
    networks:
      localnet:
        ipv4_address: 192.167.10.3

  node2:
    <<: *node-defaults
    container_name: node2
    environment:
      - ID=2
    ports:
      - "26661-26662:26656-26657"
    networks:
      localnet:
        ipv4_address: 192.167.10.4

  node3:
    <<: *node-defaults
    container_name: node3
    environment:
      - ID=3
    ports:
      - "26663-26664:26656-26657"
    networks:
      localnet:
        ipv4_address: 192.167.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.10.0/16
