# syntax=docker/dockerfile:1
FROM golang:alpine AS builder

ARG BUILD_VERSION="1.0"
ARG BUILD_DATE="2024"

ENV PACKAGES="jq util-linux vim psmisc netcat-openbsd curl git make" \
    WORKSPACE="/baronchain" \
    P2P_PORT=26656 \
    RPC_PORT=26657 \
    METRICS_PORT=26660

RUN apk update && \
    apk add --no-cache ${PACKAGES} && \
    rm -rf /var/cache/apk/* && \
    addgroup -S baronchain && \
    adduser -S -G baronchain baronchain && \
    mkdir -p ${WORKSPACE} && \
    chown -R baronchain:baronchain ${WORKSPACE}

WORKDIR ${WORKSPACE}

USER baronchain

VOLUME ${WORKSPACE}

EXPOSE ${P2P_PORT} ${RPC_PORT} ${METRICS_PORT}

HEALTHCHECK --interval=30s \
            --timeout=10s \
            --start-period=5s \
            --retries=3 \
            CMD curl -f http://localhost:${RPC_PORT}/status || exit 1

LABEL org.opencontainers.image.title="Baron Chain Testing Environment" \
      org.opencontainers.image.description="Baron Chain network testing environment" \
      org.opencontainers.image.version=${BUILD_VERSION} \
      org.opencontainers.image.created=${BUILD_DATE} \
      org.opencontainers.image.authors="liviu@baronchain.org" \
      org.opencontainers.image.vendor="Baron Chain" \
      org.opencontainers.image.source="https://github.com/baron-chain/cometbft-bc" \
      org.opencontainers.image.documentation="https://docs.baronchain.org"
